# Cloud Build configuration for automated deployment
# This file orchestrates the build and deployment process

substitutions:
  _SERVICE_NAME: rag-backend
  _REGION: us-central1
  _IMAGE_NAME: gcr.io/rag-chatbot-20250806/rag-backend

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '.']
    id: 'build-image'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--env-vars-file'
      - 'cloud_run_env.yaml'
    id: 'deploy-service'
    waitFor: ['push-image']

# Store the image in Container Registry
images:
  - '${_IMAGE_NAME}'

# Build timeout (20 minutes)
timeout: '1200s'

# Use Cloud Build machine type for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY